// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtW7xrtSHe_dGJjgFHyDr8yN_FEqL_fg8',
    appId: '1:92335594156:web:3d1aff5fac24d6251e1d09',
    messagingSenderId: '92335594156',
    projectId: 'flutterfirebasedemo-d7572',
    authDomain: 'flutterfirebasedemo-d7572.firebaseapp.com',
    databaseURL: 'https://flutterfirebasedemo-d7572-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebasedemo-d7572.firebasestorage.app',
    measurementId: 'G-2SRS1CNV59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuC7HGyZoi3TIZDCHvykNAURvI15QhyBI',
    appId: '1:92335594156:android:ef95bf9709c07cbe1e1d09',
    messagingSenderId: '92335594156',
    projectId: 'flutterfirebasedemo-d7572',
    databaseURL: 'https://flutterfirebasedemo-d7572-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebasedemo-d7572.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu_Xq0-gFvz2beaD0HX5Bu7gTlwKrYo7I',
    appId: '1:92335594156:ios:c0a6b4a61b6bd8a31e1d09',
    messagingSenderId: '92335594156',
    projectId: 'flutterfirebasedemo-d7572',
    databaseURL: 'https://flutterfirebasedemo-d7572-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebasedemo-d7572.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu_Xq0-gFvz2beaD0HX5Bu7gTlwKrYo7I',
    appId: '1:92335594156:ios:c0a6b4a61b6bd8a31e1d09',
    messagingSenderId: '92335594156',
    projectId: 'flutterfirebasedemo-d7572',
    databaseURL: 'https://flutterfirebasedemo-d7572-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebasedemo-d7572.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtW7xrtSHe_dGJjgFHyDr8yN_FEqL_fg8',
    appId: '1:92335594156:web:399baac48c8ca7f71e1d09',
    messagingSenderId: '92335594156',
    projectId: 'flutterfirebasedemo-d7572',
    authDomain: 'flutterfirebasedemo-d7572.firebaseapp.com',
    databaseURL: 'https://flutterfirebasedemo-d7572-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebasedemo-d7572.firebasestorage.app',
    measurementId: 'G-8DXPBK7CK9',
  );
}

